[(empty-world 10 10)
 (deploy 5 3 (dinosaur))
 (deploy 6 9 (dinosaur))
 (deploy 0 0 (robot :id :robot :facing :E))
 (move :forward :robot)
 (move :forward :robot)
 (move :forward :robot)
 (move :forward :robot)
 (turn :right :robot)
 (move :forward :robot)
 (move :forward :robot)
 (move :forward :robot)
 (move :forward :robot)
 (move :forward :robot)
 (move :backward :robot)
 (move :backward :robot)
 (attack :robot)
 (move :forward :robot)
 (move :forward :robot)
 (move :forward :robot)
 (move :forward :robot)
 (move :forward :robot)
 (turn :left :robot)
 (move :forward :robot)
 (move :forward :robot)
 (attack :robot)]