[(empty-world 25 25)
 (deploy 5 3 (dinosaur))
 (deploy 6 9 (dinosaur))
 (deploy 9 0 (dinosaur))
 (deploy 0 0 (robot :id :robot-1 :facing :E))
 (deploy 3 8 (robot :id :robot-2 :facing :N))
 (move :forward :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (turn :right :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (attack :robot-1)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (turn :right :robot-2)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (turn :left :robot-1)
 (move :forward :robot-1)
 (move :forward :robot-1)
 (attack :robot-1)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (move :forward :robot-2)
 (attack :robot-2)]